sudo: false

language: android
jdk: oraclejdk8

android:
  components:
  - platform-tools
  - tools
  - build-tools-27.0.3
  - android-27

before_install:
- cd Companion
- chmod +x gradlew

script:
- cd Companion
- "./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace"

notifications:
  email: true

before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

deploy:
  provider: releases
  api_key:
    secure: nB/KfuPzWrzOddy1ubl8dwzrXqcB7IchLqHpUiu/tN5XPcNolfRc83sbp1uPH7pNdCJAru5YAXnMa0L6Q5x2+uvOS9GZlSWdCbhrr+YLmPfO44wtM7xyX94lK7PLC+stkEElps3l1Ey/0CSFmSJEC8ylKiM3rqoOoFEKeyfZnK96ELWUKMT15QaRQK9pOIxF/Oo30vTaOZJAggp5OkWhlM5TW/7viwFEWGlZi9OnGO/zZeSFG0Qt0Ajjt+i38sN79w33RCnC63ic5qQhVJWK4QXEfcEMlYwc0j7VWO5PJmDHkXP7xrRBs5dubm/kNH0MgFzUAEEI1BOtU0+N5/sOYT0YpWnKXedYX6RtynRr7g1Z3UxsdN1C7T5+oy05C6h/320XKwA6t1S1bSwPlPw6Yy3NzTLVA5vSCMk3DoOUZrOVXMIKtbFutBvLwfhn0U9cB4csQ0jhkg0ivXrCzaOEprt6UM+zLH5ZfZfr7ML3vnbpcPYvxUQQ3Vik6rImnD9eYVg60krGr1oPuYos3B9SZM22UVNojUgGEAozdCSXOkZZ2mw8PZEivRUD/YytYnTqBUWMrvK57kRKofZKeBc2sm3Dz+hdZpmonrz6EErSfms9S4WER9QTX/mRMZxa3X4oHWh1oXTq+M3EP90WwMdBKL6MbllHTIdQXNoSK1x0YTc=
  file: Companion/build/outputs/apk/companion*release*.apk
  file_glob: "true"
  skip_cleanup: true
  on:
    repo: rohandhamapurkar/be-proj

after_success:
- sh set_tags.sh
