language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - build-tools-27.0.3
  - android-27
  - extra-google-m2repository
  - extra-android-m2repository
  licenses:
  - ".+"
script:
- cd Companion
- "./gradlew clean assembleDebug"
notifications:
  email: false
  slack:
    rooms:
      secure: nzWsLhpkL9Fyw8X4SqdemmeIfG3v56ljoUSKNEffgHZPes0StVRa5oO3f8KseJeuI1CmbzzI2cek8H+7PU7kWTZ4CN7uFrcEOyJyju2co8/aK4vF+Q5/k0Q9J+11l345VTpz1diIlxj8cFoiP50S3gjMTFGuxEmRC6JqNQGwQ7G3NMcPts2bErFdsXsPfP6zzMbhlvMZUdiDDxG2OrW0mJFudIpZJNFxmyiMQLXUlBqjaF6T01VSgCGkx5J+EOnc07J1RGpdwSzGscT4cPuS2EvWpSMObOdVFCL4K96qk2ajYTq5IDr5bbdvWB7niZcbg9WUOu+voHKKxJzJc1mX4y33l+yQLbvL6kvE1gn/NxtRMOaOsu6YTb/Q1D708ZqlqJk20BNoZe3l9LVOIWk3jktXOTcRhyHkGYfqwuYki7zcHHbKAStdhSzC+SU/r8XDLaz4HCviIRupXHUVI9Bp7qr2VmbE/L5TuRdJQ7pRTDMxJQ+nP37vCcoQTwDOojhfjzmTaxUua3w80ZtT4BapmsYDt7WSGtmKMKCxIwN1luWoLVAKLzSN6I5mpwufqOS2rxdOfb0oguZll5W3xIZSKBX5BL9KBFchpPPh7s+7lBTfyVHmpjjOXJ4Jy+tWqd8YEoDbPQrP696684yy1grM6NhmfMVxO+iPMwrHbD7QUXI=
sudo: false
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$ANDROID_HOME"
before_install:
  - yes | sdkmanager "platforms;android-27"
